# docker/docker-compose.yml
services:
  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - luthibox-network
    container_name: luthibox-server
    stdin_open: true    
    tty: true          
    command: ["./luthibox-server"]

  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - server
    networks:
      - luthibox-network
    container_name: luthibox-client
    stdin_open: true    
    tty: true
    command: ["./luthibox-client", "server:8080"]

networks:
  luthibox-network:
    driver: bridge